server:
  port: 8120
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mariadb://localhost:3306/sw_restaurant
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ty5355362
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update